// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import Darkmode from './darkmode';
import TableOfContents from './table-of-contents';
import InstallPwa from './install-pwa';

application.register('darkmode', Darkmode);
application.register('table-of-contents', TableOfContents);
application.register('install-pwa', InstallPwa);
