require "rails_helper"

RSpec.describe "litestream.yml" do
  # litestream.yml is generated by config/initializers/litestream.rb
  it "configures litestack replication" do
    litestream_config = YAML.load_file(Rails.root.join("config", "litestream.yml"))
    litestream_config["dbs"].each do |db|
      expect(db["path"]).to match(%r{./storage/test/\w+.sqlite3})
      expect(db.dig("replicas", 0, "url")).to match(%r{s3://})
    end
  end
end
