require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/newsletters", type: :request do
  let(:valid_attributes) { FactoryBot.attributes_for(:newsletter) }
  let(:invalid_attributes) { {title: "", content: ""} }

  describe "GET /" do
    it "renders a successful response" do
      FactoryBot.create(:newsletter)

      get admin_newsletters_path

      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      newsletter = FactoryBot.create(:newsletter)

      get admin_newsletter_path(newsletter)

      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_newsletter_path

      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      newsletter = FactoryBot.create(:newsletter)

      get edit_admin_newsletter_path(newsletter)

      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Newsletter" do
        expect {
          post admin_newsletters_path, params: {newsletter: valid_attributes}
        }.to change(Newsletter, :count).by(1)
      end

      it "redirects to the created admin_newsletter" do
        post admin_newsletters_path, params: {newsletter: valid_attributes}
        expect(response).to redirect_to(admin_newsletter_path(Newsletter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Newsletter" do
        expect {
          post admin_newsletters_path, params: {newsletter: invalid_attributes}
        }.to change(Newsletter, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_newsletters_path, params: {newsletter: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { {title: "A New Title"} }

      it "updates the requested admin_newsletter" do
        newsletter = FactoryBot.create(:newsletter)
        patch admin_newsletter_path(newsletter), params: {newsletter: new_attributes}
        newsletter.reload
        expect(newsletter.title).to eq("A New Title")
      end

      it "redirects to the admin_newsletter" do
        newsletter = FactoryBot.create(:newsletter)
        patch admin_newsletter_path(newsletter), params: {newsletter: new_attributes}
        newsletter.reload
        expect(response).to redirect_to(admin_newsletter_path(newsletter))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        newsletter = FactoryBot.create(:newsletter)
        patch admin_newsletter_path(newsletter), params: {newsletter: invalid_attributes}
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested admin_newsletter" do
      newsletter = FactoryBot.create(:newsletter)
      expect {
        delete admin_newsletter_path(newsletter)
      }.to change(Newsletter, :count).by(-1)
    end

    it "redirects to the admin_newsletters list" do
      newsletter = FactoryBot.create(:newsletter)
      delete admin_newsletter_path(newsletter)
      expect(response).to redirect_to(admin_newsletters_path)
    end
  end
end
