module.exports = {
  // Gray definitions
  'gray-1': 'var(--slate-1)',
  'gray-base': 'var(--slate-1)',
  'gray-bg-subtle': 'var(--slate-2)',
  'gray-bg': 'var(--slate-3)',
  'gray-bg-hover': 'var(--slate-4)',
  'gray-bg-active': 'var(--slate-5)',
  'gray-line': 'var(--slate-6)',
  'gray-border': 'var(--slate-7)',
  'gray-border-hover': 'var(--slate-8)',
  'gray-solid': 'var(--slate-9)',
  'gray-solid-hover': 'var(--slate-10)',
  'gray-solid-text': '#fff',
  'gray-text': 'var(--slate-11)',
  'gray-12': 'var(--slate-12)',
  'gray-text-contrast': 'var(--slate-12)',
  'gray-solid-high-contrast': 'var(--slate-12)',
  'gray-solid-high-contrast-text': 'var(--gray-1)',
  'gray-2-translucent': '#1b1d1eb3',

  // Accent definitions
  'accent-base': 'var(--accent-base)',
  'accent-bg-subtle': 'var(--accent-bg-subtle)',
  'accent-bg': 'var(--accent-bg)',
  'accent-bg-hover': 'var(--accent-bg-hover)',
  'accent-bg-active': 'var(--accent-bg-active)',
  'accent-line': 'var(--accent-line)',
  'accent-border': 'var(--accent-border)',
  'accent-border-hover': 'var(--accent-border-hover)',
  'accent-solid': 'var(--accent-solid)',
  'accent-solid-hover': 'var(--accent-solid-hover)',
  'accent-solid-text': 'var(--accent-solid-text)',
  'accent-text': 'var(--accent-text)',
  'accent-text-contrast': 'var(--accent-text-contrast)',
  'accent-solid-high-contrast': 'var(--accent-solid-high-contrast)',
  'accent-solid-high-contrast-text': 'var(--accent-solid-high-contrast-text)',
  'accent-alpha-ring': 'var(--accent-alpha-ring)',

  // Component definitions
  overlay: '#09090bcc',
  background: 'var(--accent-base)',
  'bg-card-solid': 'var(--background)',
  'bg-card-translucent': 'var(--gray-2-translucent)',
  'gray-muted': '#a1a1aa',
};
