#!/usr/bin/env ruby

require "bundler/setup"
require "json"
require "color_conversion"
require "active_support/deprecation"
require "active_support/deprecator"
require "active_support/core_ext/string"

Color = ColorConversion::Color

puts ":root {"

color_json = JSON.parse(File.read("./script/uicolors-hex.json"))

color_json.each do |color, weight_hex_pairs|
  weight_hex_pairs.each do |weight, hex|
    hsl = Color.new(hex).hsl
    hsla_string = "hsla(#{hsl[:h]}, #{hsl[:s]}%, #{hsl[:l]}%, 1)"
    puts "\s\s--color-#{color.dasherize}-#{weight}: #{hsla_string};"
  end
end

puts "}"
