#!/usr/bin/env ruby

require "bundler/setup"
require "color_conversion"

Color = ColorConversion::Color

current_color = nil
hex = nil
weight = nil

puts ":root {"

File.readlines("./input/tailwind-colors-hex").each do |line|
  value = line.strip
  if line.start_with?("#")
    hex = value
  elsif line.start_with?(/\d/)
    weight = value
  else
    current_color = value.downcase
  end

  if hex && weight && current_color
    hsl = Color.new(hex).hsl
    hsla_string = "hsla(#{hsl[:h]}, #{hsl[:s]}%, #{hsl[:l]}%, 1)"
    puts "\s\s--color-#{current_color}-#{weight}: #{hsla_string};"

    hex = nil
    weight = nil
  end
end

puts "}"
